import type { PlatformCapabilityMap, PlatformKey } from "@/lib/platforms/types";

export const PLATFORM_CAPABILITIES: Record<PlatformKey, PlatformCapabilityMap> = {
  linkedin: {
    text: true,
    image: true,
    multiImage: true,
    video: true,
    link: true,
    scheduling: true,
    analytics: true,
    memberPublishing: true,
    organizationPublishing: true,
  },
  x: {
    text: true,
    image: true,
    multiImage: true,
    video: true,
    link: true,
    scheduling: true,
    analytics: true,
    memberPublishing: true,
    organizationPublishing: false,
  },
  facebook: {
    text: true,
    image: true,
    multiImage: true,
    video: true,
    link: true,
    scheduling: true,
    analytics: true,
    memberPublishing: false,
    organizationPublishing: true,
  },
  instagram: {
    text: true,
    image: true,
    multiImage: true,
    video: true,
    link: false,
    scheduling: true,
    analytics: true,
    memberPublishing: false,
    organizationPublishing: true,
  },
  threads: {
    text: true,
    image: true,
    multiImage: true,
    video: true,
    link: true,
    scheduling: true,
    analytics: false,
    memberPublishing: true,
    organizationPublishing: false,
  },
  youtube: {
    text: false,
    image: false,
    multiImage: false,
    video: true,
    link: false,
    scheduling: true,
    analytics: true,
    memberPublishing: true,
    organizationPublishing: false,
  },
  tiktok: {
    text: false,
    image: false,
    multiImage: false,
    video: true,
    link: false,
    scheduling: true,
    analytics: true,
    memberPublishing: true,
    organizationPublishing: false,
  },
};
